# Generated by Django 6.0 on 2026-01-03 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-timestamp"]},
        ),
    ]
