# Generated by Django 6.0 on 2026-01-03 05:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0004_alter_image_image_alter_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
