# Generated by Django 6.0 on 2026-01-03 05:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0005_image_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
