# Generated by Django 6.0 on 2026-01-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0007_alter_image_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="total_views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
